config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  post 'results' => 'home#results'

  get 'results' => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def results

    # params coming the form in the index page
    # capitalization (or lack thereof) shouldn't be a problem
    @food = 'corndogs'
    @location = params[:location]

    # the client search set up by the Yelp gem
    # takes only two arguments, so if I want to
    # pass more, I can include them in a hash
    parameters = { term: @food, limit: 6 }

    # using the Yelp gem to make the API call
    # the two arguments passed are the location I
    # want to search for, and then the extra parameters
    @results = Yelp.client.search(@location, parameters)

   
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well mtop-50">
      <h1 class="center-it">Do you ever just feel like<br>eating a corndog?</h1>
      <div class="col-md-6 col-md-offset-3">
      <%= form_tag results_path do %>
        <div class="form-group">
          <%= text_field_tag :location, nil, placeholder: "Where the heck are ya?", class: "form-control", required: true %>
        </div>
        <div class="form-group center-it">
          <%= submit_tag "FIND THE NEAREST CORNDOG", class: "btn btn-danger" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/results.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="well transparent">
        <h1>Let's Get Some <%= @food.capitalize %></h1>
      </div>
    </div>
  </div>
  <div class="row">
    <% @results.businesses.each do |biz| %>
      <div class="col-md-4">
        <div class="well center-it same">
          <h3><%= biz.name %></h3>
          <p>
            <% if biz.image_url != nil %>
              <%= image_tag biz.image_url, alt: "Restaurant Photo" %>
            <% end %>
          </p>  
          <p>
            <%= image_tag biz.rating_img_url, alt: "Yelp Rating" %>
          </p>
          <p>
            <% biz.location.display_address.each do |add_line| %>
              <%= add_line %><br />
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>